{% set name = "writer-sdk" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/writer_sdk-{{ version }}.tar.gz
  sha256: 4e36af957180119d6d32cf7eb3925e9b1dd3fb9576b84008b76f225fe16f550b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.10,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - jiter >=0.4.0,<1

test:
  imports:
    - writerai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/writer/writer-python
  summary: The official Python library for the Writer API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
